"""initial_schema

Revision ID: 0633fbfcda59
Revises: 
Create Date: 2026-07-02 19:55:52.592803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0633fbfcda59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scada_analytics_oee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linea', sa.String(length=50), nullable=False),
    sa.Column('timestamp_calculo', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disponibilidad', sa.Float(), nullable=False),
    sa.Column('rendimiento', sa.Float(), nullable=False),
    sa.Column('calidad', sa.Float(), nullable=False),
    sa.Column('oee_total', sa.Float(), nullable=False),
    sa.Column('minutos_operativos', sa.Float(), nullable=False),
    sa.Column('minutos_parada', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scada_analytics_oee_id'), 'scada_analytics_oee', ['id'], unique=False)
    op.create_index(op.f('ix_scada_analytics_oee_linea'), 'scada_analytics_oee', ['linea'], unique=False)
    op.create_index(op.f('ix_scada_analytics_oee_timestamp_calculo'), 'scada_analytics_oee', ['timestamp_calculo'], unique=False)
    op.create_table('scada_history_dosificacion_global',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('m_stock_rpm', sa.Float(), nullable=False),
    sa.Column('dosificacion_mot_m', sa.Float(), nullable=False),
    sa.Column('porcentaje_mot_mezclador_m', sa.Float(), nullable=False),
    sa.Column('motor_c1_m', sa.Float(), nullable=False),
    sa.Column('motor_c2_m', sa.Float(), nullable=False),
    sa.Column('porcentaje_m_c1_m', sa.Float(), nullable=True),
    sa.Column('porcentaje_m_c2_m', sa.Float(), nullable=True),
    sa.Column('s1_stock_rpm', sa.Float(), nullable=True),
    sa.Column('dosificacion_mot_s1', sa.Float(), nullable=True),
    sa.Column('porcentaje_mot_mezclador_s1', sa.Float(), nullable=True),
    sa.Column('motor_c1_s1', sa.Float(), nullable=True),
    sa.Column('porcentaje_m_c1_s1', sa.Float(), nullable=True),
    sa.Column('s2_stock_rpm', sa.Float(), nullable=True),
    sa.Column('dosificacion_mot_s2', sa.Float(), nullable=True),
    sa.Column('porcentaje_mot_mezclador_s2', sa.Float(), nullable=True),
    sa.Column('motor_c1_s2', sa.Float(), nullable=True),
    sa.Column('porcentaje_m_c1_s2', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scada_history_dosificacion_global_id'), 'scada_history_dosificacion_global', ['id'], unique=False)
    op.create_index(op.f('ix_scada_history_dosificacion_global_timestamp'), 'scada_history_dosificacion_global', ['timestamp'], unique=False)
    op.create_table('scada_history_extrusora_meltblown',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pv_zona1', sa.Float(), nullable=False),
    sa.Column('sp_zona1', sa.Float(), nullable=False),
    sa.Column('pv_zona2', sa.Float(), nullable=False),
    sa.Column('sp_zona2', sa.Float(), nullable=False),
    sa.Column('pv_zona3', sa.Float(), nullable=False),
    sa.Column('sp_zona3', sa.Float(), nullable=False),
    sa.Column('pv_zona4', sa.Float(), nullable=False),
    sa.Column('sp_zona4', sa.Float(), nullable=False),
    sa.Column('pv_zona5', sa.Float(), nullable=False),
    sa.Column('sp_zona5', sa.Float(), nullable=False),
    sa.Column('pv_zona6', sa.Float(), nullable=False),
    sa.Column('sp_zona6', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scada_history_extrusora_meltblown_id'), 'scada_history_extrusora_meltblown', ['id'], unique=False)
    op.create_index(op.f('ix_scada_history_extrusora_meltblown_timestamp'), 'scada_history_extrusora_meltblown', ['timestamp'], unique=False)
    op.create_table('scada_history_extrusora_s1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pv_zona1', sa.Float(), nullable=False),
    sa.Column('sp_zona1', sa.Float(), nullable=False),
    sa.Column('pv_zona2', sa.Float(), nullable=False),
    sa.Column('sp_zona2', sa.Float(), nullable=False),
    sa.Column('pv_zona3', sa.Float(), nullable=False),
    sa.Column('sp_zona3', sa.Float(), nullable=False),
    sa.Column('pv_zona4', sa.Float(), nullable=False),
    sa.Column('sp_zona4', sa.Float(), nullable=False),
    sa.Column('pv_zona5', sa.Float(), nullable=False),
    sa.Column('sp_zona5', sa.Float(), nullable=False),
    sa.Column('pv_zona6', sa.Float(), nullable=False),
    sa.Column('sp_zona6', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scada_history_extrusora_s1_id'), 'scada_history_extrusora_s1', ['id'], unique=False)
    op.create_index(op.f('ix_scada_history_extrusora_s1_timestamp'), 'scada_history_extrusora_s1', ['timestamp'], unique=False)
    op.create_table('scada_history_extrusora_s2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pv_zona1', sa.Float(), nullable=False),
    sa.Column('sp_zona1', sa.Float(), nullable=False),
    sa.Column('pv_zona2', sa.Float(), nullable=False),
    sa.Column('sp_zona2', sa.Float(), nullable=False),
    sa.Column('pv_zona3', sa.Float(), nullable=False),
    sa.Column('sp_zona3', sa.Float(), nullable=False),
    sa.Column('pv_zona4', sa.Float(), nullable=False),
    sa.Column('sp_zona4', sa.Float(), nullable=False),
    sa.Column('pv_zona5', sa.Float(), nullable=False),
    sa.Column('sp_zona5', sa.Float(), nullable=False),
    sa.Column('pv_zona6', sa.Float(), nullable=False),
    sa.Column('sp_zona6', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scada_history_extrusora_s2_id'), 'scada_history_extrusora_s2', ['id'], unique=False)
    op.create_index(op.f('ix_scada_history_extrusora_s2_timestamp'), 'scada_history_extrusora_s2', ['timestamp'], unique=False)
    op.create_table('scada_history_motores_velocidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sp_bomba_hiladora', sa.Float(), nullable=False),
    sa.Column('pv_bomba_hiladora', sa.Float(), nullable=False),
    sa.Column('sp_m_incoex_rpm', sa.Float(), nullable=False),
    sa.Column('pv_m_incoex_rpm', sa.Float(), nullable=False),
    sa.Column('sp_m_monomero', sa.Float(), nullable=False),
    sa.Column('pv_m_monomero', sa.Float(), nullable=False),
    sa.Column('sp_m_cooling', sa.Float(), nullable=False),
    sa.Column('pv_m_cooling', sa.Float(), nullable=False),
    sa.Column('sp_m_chiladora', sa.Float(), nullable=False),
    sa.Column('pv_m_chiladora', sa.Float(), nullable=False),
    sa.Column('sp_m_suction', sa.Float(), nullable=False),
    sa.Column('pv_m_suction', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scada_history_motores_velocidades_id'), 'scada_history_motores_velocidades', ['id'], unique=False)
    op.create_index(op.f('ix_scada_history_motores_velocidades_timestamp'), 'scada_history_motores_velocidades', ['timestamp'], unique=False)
    op.create_table('scada_history_proceso_mecanico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sp_rbody', sa.Float(), nullable=False),
    sa.Column('pv_rbody', sa.Float(), nullable=False),
    sa.Column('sp_coolarea', sa.Float(), nullable=False),
    sa.Column('pv_coolarea', sa.Float(), nullable=False),
    sa.Column('sp_coolfan', sa.Float(), nullable=False),
    sa.Column('pv_coolfan', sa.Float(), nullable=False),
    sa.Column('sv1_filter_ex_pre', sa.Float(), nullable=False),
    sa.Column('sv2_filter_ex_pre', sa.Float(), nullable=False),
    sa.Column('pv_filter_ex_pre', sa.Float(), nullable=False),
    sa.Column('sp_die_pre', sa.Float(), nullable=False),
    sa.Column('pv_die_pre', sa.Float(), nullable=False),
    sa.Column('rgrafito_temp_sp', sa.Float(), nullable=False),
    sa.Column('rgrafito_temp_pv', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scada_history_proceso_mecanico_id'), 'scada_history_proceso_mecanico', ['id'], unique=False)
    op.create_index(op.f('ix_scada_history_proceso_mecanico_timestamp'), 'scada_history_proceso_mecanico', ['timestamp'], unique=False)
    op.create_table('scada_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scada_permissions_id'), 'scada_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_scada_permissions_name'), 'scada_permissions', ['name'], unique=True)
    op.create_table('scada_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scada_roles_id'), 'scada_roles', ['id'], unique=False)
    op.create_index(op.f('ix_scada_roles_name'), 'scada_roles', ['name'], unique=True)
    op.create_table('scada_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=True),
    sa.Column('plc_area', sa.String(length=10), nullable=True),
    sa.Column('plc_db', sa.Integer(), nullable=True),
    sa.Column('plc_width', sa.String(length=2), nullable=True),
    sa.Column('plc_byte', sa.Integer(), nullable=True),
    sa.Column('plc_bit', sa.Integer(), nullable=True),
    sa.Column('limit_high_high', sa.Float(), nullable=True),
    sa.Column('limit_high', sa.Float(), nullable=True),
    sa.Column('limit_low', sa.Float(), nullable=True),
    sa.Column('limit_low_low', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scada_tags_id'), 'scada_tags', ['id'], unique=False)
    op.create_index(op.f('ix_scada_tags_tag_name'), 'scada_tags', ['tag_name'], unique=True)
    op.create_table('scada_alarms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('alarm_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('timestamp_active', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timestamp_ack', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_cleared', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['scada_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scada_alarms_id'), 'scada_alarms', ['id'], unique=False)
    op.create_table('scada_role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['scada_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['scada_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('scada_tag_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['scada_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scada_tag_history_id'), 'scada_tag_history', ['id'], unique=False)
    op.create_index(op.f('ix_scada_tag_history_timestamp'), 'scada_tag_history', ['timestamp'], unique=False)
    op.create_table('scada_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['scada_roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scada_users_email'), 'scada_users', ['email'], unique=True)
    op.create_index(op.f('ix_scada_users_id'), 'scada_users', ['id'], unique=False)
    op.create_index(op.f('ix_scada_users_username'), 'scada_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scada_users_username'), table_name='scada_users')
    op.drop_index(op.f('ix_scada_users_id'), table_name='scada_users')
    op.drop_index(op.f('ix_scada_users_email'), table_name='scada_users')
    op.drop_table('scada_users')
    op.drop_index(op.f('ix_scada_tag_history_timestamp'), table_name='scada_tag_history')
    op.drop_index(op.f('ix_scada_tag_history_id'), table_name='scada_tag_history')
    op.drop_table('scada_tag_history')
    op.drop_table('scada_role_permissions')
    op.drop_index(op.f('ix_scada_alarms_id'), table_name='scada_alarms')
    op.drop_table('scada_alarms')
    op.drop_index(op.f('ix_scada_tags_tag_name'), table_name='scada_tags')
    op.drop_index(op.f('ix_scada_tags_id'), table_name='scada_tags')
    op.drop_table('scada_tags')
    op.drop_index(op.f('ix_scada_roles_name'), table_name='scada_roles')
    op.drop_index(op.f('ix_scada_roles_id'), table_name='scada_roles')
    op.drop_table('scada_roles')
    op.drop_index(op.f('ix_scada_permissions_name'), table_name='scada_permissions')
    op.drop_index(op.f('ix_scada_permissions_id'), table_name='scada_permissions')
    op.drop_table('scada_permissions')
    op.drop_index(op.f('ix_scada_history_proceso_mecanico_timestamp'), table_name='scada_history_proceso_mecanico')
    op.drop_index(op.f('ix_scada_history_proceso_mecanico_id'), table_name='scada_history_proceso_mecanico')
    op.drop_table('scada_history_proceso_mecanico')
    op.drop_index(op.f('ix_scada_history_motores_velocidades_timestamp'), table_name='scada_history_motores_velocidades')
    op.drop_index(op.f('ix_scada_history_motores_velocidades_id'), table_name='scada_history_motores_velocidades')
    op.drop_table('scada_history_motores_velocidades')
    op.drop_index(op.f('ix_scada_history_extrusora_s2_timestamp'), table_name='scada_history_extrusora_s2')
    op.drop_index(op.f('ix_scada_history_extrusora_s2_id'), table_name='scada_history_extrusora_s2')
    op.drop_table('scada_history_extrusora_s2')
    op.drop_index(op.f('ix_scada_history_extrusora_s1_timestamp'), table_name='scada_history_extrusora_s1')
    op.drop_index(op.f('ix_scada_history_extrusora_s1_id'), table_name='scada_history_extrusora_s1')
    op.drop_table('scada_history_extrusora_s1')
    op.drop_index(op.f('ix_scada_history_extrusora_meltblown_timestamp'), table_name='scada_history_extrusora_meltblown')
    op.drop_index(op.f('ix_scada_history_extrusora_meltblown_id'), table_name='scada_history_extrusora_meltblown')
    op.drop_table('scada_history_extrusora_meltblown')
    op.drop_index(op.f('ix_scada_history_dosificacion_global_timestamp'), table_name='scada_history_dosificacion_global')
    op.drop_index(op.f('ix_scada_history_dosificacion_global_id'), table_name='scada_history_dosificacion_global')
    op.drop_table('scada_history_dosificacion_global')
    op.drop_index(op.f('ix_scada_analytics_oee_timestamp_calculo'), table_name='scada_analytics_oee')
    op.drop_index(op.f('ix_scada_analytics_oee_linea'), table_name='scada_analytics_oee')
    op.drop_index(op.f('ix_scada_analytics_oee_id'), table_name='scada_analytics_oee')
    op.drop_table('scada_analytics_oee')
    # ### end Alembic commands ###
